/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.maicon.techstartpro.view;

import javax.swing.JOptionPane;

/**
 *
 * @author MAICON
 */
public class MainForm extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form FormPrincipal
     */
    public MainForm() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    @Override
    public void run() {
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void exit() {
        int dialogResult = JOptionPane.showConfirmDialog(null, "Do you really want exit?", "Alert", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (dialogResult == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuProduct = new javax.swing.JMenu();
        menuCategories = new javax.swing.JMenu();
        menuAbout = new javax.swing.JMenu();
        menuExit = new javax.swing.JMenu();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 824, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );

        menuProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-produto-25.png"))); // NOI18N
        menuProduct.setText("Products");
        menuProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuProductMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuProduct);

        menuCategories.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-categorizar-25.png"))); // NOI18N
        menuCategories.setText("Categories");
        menuCategories.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCategoriesMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuCategories);

        menuAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-sobre-25.png"))); // NOI18N
        menuAbout.setText("About");
        menuAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAboutMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuAbout);

        menuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-off-25.png"))); // NOI18N
        menuExit.setText("Exit");
        menuExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuExitMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuExit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuExitMouseClicked
        exit();
    }//GEN-LAST:event_menuExitMouseClicked

    private void menuCategoriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCategoriesMouseClicked
        UploadCategoryForm formUploadCategory = new UploadCategoryForm();
        formUploadCategory.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_menuCategoriesMouseClicked

    private void menuAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAboutMouseClicked
        AboutForm aboutForm = new AboutForm();
        aboutForm.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_menuAboutMouseClicked

    private void menuProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuProductMouseClicked
        ListProductsForm formListProducts = new ListProductsForm();
        formListProducts.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_menuProductMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuAbout;
    private javax.swing.JMenu menuCategories;
    private javax.swing.JMenu menuExit;
    private javax.swing.JMenu menuProduct;
    // End of variables declaration//GEN-END:variables
}
